import Head from "next/head";
import { api } from "~/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const { data } = api.games.getAll.useQuery();
  const user = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user.isSignedIn) {
      router.push("/home").catch(() => console.error("ERROR CAN'T GO HOME"));
    }
  }, [user.isSignedIn, router]);

  return (
    <>
      <Head>
        <title>PlayScripe - Track Your Gaming Backlog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="h-screen bg-opacity-20  flex items-center justify-center bg-LastOfUs2">
        <div className="flex flex-col md:flex-row items-center overflow-hidden">
          <div className="w-full text-center flex flex-col items-center justify-center">
            <h1 className="text-3xl font-bold text-white mb-4">
              Welcome to PlayScripe
            </h1>
            <p className="text-sm text-gray-300 mb-8 italic">
              Letterboxd, but for your gaming backlog.
            </p>
            {!user.isSignedIn && (
              <SignInButton>
                <button className="px-6 py-3 bg-blue-600 text-white font-medium text-lg rounded-lg shadow-lg hover:bg-blue-700 transition-all">
                  Sign In to Get Started
                </button>
              </SignInButton>
            )}
          </div>
          <div className="md:w-1/2 px-8 py-20 flex items-center bg-cover bg-center"></div>
          </div>
          </div>
      </main>
    </>
  );
}
