import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const { data } = api.games.getAll.useQuery();
  const user = useUser();
  return (
    <>
      <Head>
        <title>PlayScripe - keeping track of your gaming backlog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-r from-purple-500 to-pink-500 ">
        <div>
          <div className="mx-4 my-20 w-full max-w-md rounded-lg bg-white p-8 shadow-lg">
            <h1 className="mb-4 text-center text-2xl font-bold text-red-950">
              Landing screen i guess
            </h1>
            <p className="text-center text-gray-700">
              This is sample page cause idk how to design shit
            </p>
            <div className="flex justify-center mt-4">
              {!user.isSignedIn && <SignInButton></SignInButton>}
              {!!user.isSignedIn && <SignOutButton></SignOutButton>}
            </div>
          </div>
        </div>
        <div>
       
        </div>
      </main>
    </>
  );
}
