import Head from "next/head";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import GamesPage from "./games/create";
import { useRouter } from "next/router";
import NavBar from "~/component/navbar";


export default function Home() {
  const { data } = api.games.getAll.useQuery();
  const user = useUser();
  const router = useRouter();
  

  
  return (
    <>
      <Head>
        <title>PlayScripe - keeping track of your gaming backlog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="h-screen flex items-center justify-center ">
          <div className="mx-4 my-20 w-full max-w-md rounded-lg bg-[#41434A]">
            <h1 className="text-center font-bold text-white">
              Join PlayScripe
            </h1>
            <h1 className="mb-4 text-center text-white text-xs font-style: italic">
              Your Life in Games
            </h1>
            <p className="text-center text-white">
              This is sample page cause idk how to design shit
            </p>
            <div className="mt-4 flex justify-center">
              {!user.isSignedIn && <SignInButton></SignInButton>}
              {!!user.isSignedIn && (
                <button> Go to Creatwafwafwafwae</button>
              )}
            </div>
          </div>
        </div>
        <div></div>
      </main>
    </>
  );
}
